apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9deploy
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: web    # (1) Pod 작성 시 이 부분 (label -> app:web) 포함되어야 함
  template:       # 여기부터 Pod 작성
    metadata:
      labels:
        app: web  # 반드시 (1)과 동일해야 함
    spec:
      containers:
        - name: aws9ctn
          image: xxoznge0929/aws9:blue
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port
    port: 8080      # cluster IP의 Port 번호
    protocol: TCP
    targetPort: 80  # Container Port 번호
    nodePort: 30080
  selector:
    app: web        # Pod의 label 지정해주기
